name: Crawler

on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           token: ${{ secrets.ACCESS_TOKEN }}
      - name: Use Python 3.x
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set Timezone
        uses: zcong1993/setup-timezone@v1.1.1
        with: 
          timezone: 'Asia/Shanghai'
      - name: Crawler
        run: python BingWallpaper.py
      - name: Commit
        run: |
          git config --global user.email 393893729@qq.com
          git config --global user.name WangZhiYao
          git add .
          git commit -m "Updated: `date +'%Y-%m-%d %H:%M:%S'`" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: master 
